### ISSUE TITLE
why does it keep crashing for me

### ISSUE THREAD

**Issue by brickyosu** [asimon0v/nong-manager#1] opened 2023-05-31 23:10 UTC
when i search the id, it crashes

**Comment by adarift** [comment] 2023-06-04 17:00
does it show the error?

**Comment by OMEGA6405** [comment] 2023-07-30 21:16
@asimon0v my friend is having the same problem, here's the error![Captura_de_pantalla_2023-07-30_170957.png](https://github.com/asimon0v/nong-manager/assets/98067930/3ed3e271-3e4b-41e1-a88e-4ddd68d57a37)

**Comment by asimon0v** [comment] 2023-07-30 21:19
@OMEGA6405 Sorry, but I do not speak Spanish. If you or your friend could translate it to me, that might help in fixing the problem.

**Comment by OMEGA6405** [comment] 2023-07-30 21:20
Already working on it

**Comment by asimon0v** [comment] 2023-07-30 21:21
@OMEGA6405 Sorry, but I do not speak Spanish. If you or your friend could translate it to me, that might help in fixing the problem.

**Comment by asimon0v** [comment] 2023-07-30 21:21
Ok, thank you!

**Comment by OMEGA6405** [comment] 2023-07-30 21:26
@asimon0v ![Captura_de_pantalla_2023-07-30_172329.png](https://github.com/asimon0v/nong-manager/assets/98067930/f6f81c6e-299b-4f78-805c-6700c51ef34e)

**Comment by asimon0v** [comment] 2023-07-30 21:34
@OMEGA6405 Ok, got it. Can you please ask your friend to go to this [link](https://songfilehub.com/api/v1/nongs?id=546561) and to say what they get in response. If they get json response, simillar to this: 
```
{"status":200,"songs":[{"file":null,"isMashup":false,"name":"Aerial Gleam","$key":"","state":"rated","nameLowercase":"aerial gleam","ytVideoID":"eyZjKtrGVYw","songID":"546561","levelNameMobile":"Aerial gleam","songName":"Flo Rida - I Cry (NIGHTkilla Remix)","downloadUrl":"https://cdn.discordapp.com/attachments/938033986201088020/1034752500965838879/546561.mp3","songNameCaps":"FLO RIDA - I CRY (NIGHTKILLA REMIX)","levelNameCaps":"AERIAL GLEAM","songNameLowercase":"flo rida - i cry (nightkilla remix)","songNameMobile":"Flo rida - i cry (nightkilla remix)","songURL":""}]}
```
,then the problem is in the manager itself. If they are getting any kind of error, it means that website is not working for them in particular (maybe blocked in their country because of copyright claims) and there is nothing that I can do with it.

**Comment by OMEGA6405** [comment] 2023-07-30 21:44
@asimon0v took too long to respond also he said the site won't load so yeah it probably got blocked

**Comment by asimon0v** [comment] 2023-07-31 03:11
Ok, closing the issue then

**Closed** 2023-07-31 03:12 UTC
